Fix/job query changes
mimiro-io/datahub pull request #116
Opened 2022-02-08 13:32 UTC by rompetroll

In rare cases, when a storage batch contained multiple changes for the same entity, and the changes were small enough to let their json-reprensentation have the same storage size, then a key collision could happen. This PR fixes those cases by making sure every change id is unique using a batch sequence number.

2022-02-08 15:56 UTC, gra-moore requested changes
Please can you look at my comments.

2022-02-08 15:56 UTC, gra-moore commented on internal/server/dataset.go
> +			if localLatests[rid] != nil {
i think you can do a lookup and it also return an OK if found. prevLocalJson, found = localLatests[rid]. It would save a second lookup.

2022-02-08 15:56 UTC, gra-moore commented on internal/server/dataset.go
> +				err = json.Unmarshal(prevLocalJson, prevLocalEntity)
Should this error be handled?

2022-02-09 09:34 UTC, rompetroll commented on internal/server/dataset.go
> +			if localLatests[rid] != nil {
agreed

2022-02-09 09:57 UTC, gra-moore approved these changes

2022-02-09 09:57 UTC, merged