Expand on query-functions and transforms
mimiro-io/datahub pull request #51
Opened 2021-05-14 08:01 UTC by 4hlberg

2021-05-14 11:05 UTC, gra-moore requested changes
see comments

2021-05-14 11:05 UTC, gra-moore commented on DOCUMENTATION.md
> +The query is incoming if you are looking for entities that reference the id of the entity your are starting with in their references and it is outgoing if the starting entity is referencing other ent
This is sentence is too long. Try re-writing in shorted sentences.

2021-05-14 11:05 UTC, gra-moore commented on DOCUMENTATION.md
> +        "ns1:id":"ns0:starting-entity"
ns1:id is confusing. Suggest name it something a bit more informative. e.g. ns1:personid, maybe also add rdf:type to both entities to help understanding.

2021-05-14 11:05 UTC, gra-moore commented on DOCUMENTATION.md
> +        "ns1:id":"ns2:id-of-referenced-entity"
again prop name can be better.

2021-05-14 11:05 UTC, gra-moore commented on DOCUMENTATION.md
>      [ "entity-id" , "property uri", { "id" : "related entity" } ]
I feel this structure can be better communicated.

2021-05-14 12:48 UTC, 4hlberg commented on DOCUMENTATION.md
> +The query is incoming if you are looking for entities that reference the id of the entity your are starting with in their references and it is outgoing if the starting entity is referencing other ent
Rewritten, check it out

2021-05-14 12:48 UTC, 4hlberg commented on DOCUMENTATION.md
> +        "ns1:id":"ns0:starting-entity"
Changed a bit, see if that makes more sense

2021-05-14 12:48 UTC, 4hlberg commented on DOCUMENTATION.md
> +        "ns1:id":"ns2:id-of-referenced-entity"
See above

2021-05-14 12:48 UTC, 4hlberg commented on DOCUMENTATION.md
>      [ "entity-id" , "property uri", { "id" : "related entity" } ]
Expanded on the structure here, have not changed the wording in the description, but rather clarified with examples.

2021-05-20 06:21 UTC, gra-moore approved these changes

2021-05-20 06:21 UTC, merged